### ISSUE TITLE
Dash/dock shows a dot instead of the Name stanza in systemd-manager.desktop

### ISSUE THREAD

**Issue by glitsj16** [mmstick/systemd-manager#40] opened 2017-03-14 22:34 UTC
Realizing this would qualify for the 'most un-important question on github award', I'm just wondering why systemd-manager shows a dot (.) when hovering over it's application icon instead of the Name=... stanza supplied in systemd-manager.desktop file. Any ideas on getting that to work?

Regards.

**Comment by mmstick** [comment] 2017-03-15 16:20
Already reported here https://github.com/mmstick/systemd-manager/issues/30

Basically, I have no idea. The name of the application is set in the Glade file, but the application is not using that name. I don't know what that is. Seems to happen with my other GTK3 application that uses a HeaderBar. It only happens when using a HeaderBar.

**Comment by glitsj16** [comment] 2017-03-16 02:40
Apologies for missing https://github.com/mmstick/systemd-manager/issues/30. It is indeed the same issue. I dug into some rust Gtk documentation and I think I have a fix. Basically systemd-manager is missing the WM_CLASS, which can be easily added via https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass. Although that doc mentions this is not needed and deprecated, my guess is it can still be useful for CSD apps. Tested it on Arch Linux / Ubuntu and it works as expected. Thoughts?

**Comment by mmstick** [comment] 2017-03-16 13:48
The issue is now resolved, so I am closing this.

**Closed by mmstick** 2017-03-16 13:48 UTC
