### ISSUE TITLE
panicked at 'called `Option::unwrap() on exit

### ISSUE THREAD

**Issue by alex285** [mmstick/systemd-manager#8] opened 2016-05-17 09:17 UTC
When exiting

Gtk-WARNING **: Allocating size to GtkWindow 0x55ed50ade290 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330

rustc 1.7.0 (a5d1e7a59 2016-02-29)
gtk 321
rawhide

**Comment by alex285** [comment] 2016-05-17 09:32
bt:

thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:     0x5615e5823800 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x5615e5826405 - panicking::default_handler::_<closure>::closure.42502
   3:     0x5615e5825eaf - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x5615e58145b6 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x5615e5814b28 - sys_common::unwind::begin_unwind_fmt::h878e9fd8b85e0857hbt
   6:     0x5615e5822e41 - rust_begin_unwind
   7:     0x5615e5857f9f - panicking::panic_fmt::h9f005ee999496200zYL
   8:     0x5615e5858278 - panicking::panic::h94bef08fa1f352c06WL
   9:     0x5615e57c0f7d - option::Option<T>::unwrap::h16515609606882990218
                        at ../src/libcore/macros.rs:21
  10:     0x5615e57c0a77 - systemd_gui::launch::_<closure>::closure.14181
                        at src/systemd_gui.rs:172
  11:     0x5615e5808851 - extern $u22$rust.call$u22$$u20$fn$LP$$RF$for$LT$$u27$r$C$$u20$$u27$r$GT$$u20$core..ops..Fn$LP$$RF$$u27$r$u20$auto..list_box..ListBox$C$$u20$$RF$$u27$r$u20$core..option..Option$LT$auto..list_box_row..ListBoxRow$GT$$RP$$u20$$u2b$$u20$$u27$static$C$$u20$$LP$$RF$$u27$static$u20$auto..list_box..ListBox$C$$u20$$RF$$u27$static$u20$core..option..Option$LT$auto..list_box_row..ListBoxRow$GT$$RP$$RP$::object_shim.106808::h1f087ca9251b8f83
  12:     0x5615e5808782 - auto::list_box::row_selected_trampoline::__rust_abi
                        at /home/alex/.multirust/toolchains/stable/cargo/git/checkouts/gtk-373d3cc909970d2e/master/src/auto/list_box.rs:312
  13:     0x5615e58085f4 - auto::list_box::row_selected_trampoline::h713e5370433d0b1b65F
  14:     0x7f2930eb844f - g_cclosure_marshal_VOID__OBJECTv
  15:     0x7f2930eb55f3 - <unknown>
  16:     0x7f2930ecfdb8 - g_signal_emit_valist
  17:     0x7f2930ed041e - g_signal_emit
  18:     0x7f2931ef698c - <unknown>
  19:     0x7f2930eb844f - g_cclosure_marshal_VOID__OBJECTv
  20:     0x7f2930eb55f3 - <unknown>
  21:     0x7f2930ecfdb8 - g_signal_emit_valist
  22:     0x7f2930ed041e - g_signal_emit
  23:     0x7f2931e2b6ac - gtk_container_remove
  24:     0x7f293206a20e - <unknown>
  25:     0x7f2930ebbac8 - g_object_run_dispose
  26:     0x7f2931ef229a - <unknown>
  27:     0x7f2931e2d3df - <unknown>
  28:     0x7f2930eb531e - g_closure_invoke
  29:     0x7f2930ec7725 - <unknown>
  30:     0x7f2930ed003e - g_signal_emit_valist
  31:     0x7f2930ed041e - g_signal_emit
  32:     0x7f293206a2e7 - <unknown>
  33:     0x7f2930ebbac8 - g_object_run_dispose
  34:     0x7f2931e2d3df - <unknown>
  35:     0x7f293205a127 - <unknown>
  36:     0x7f2930eb531e - g_closure_invoke
  37:     0x7f2930ec7725 - <unknown>
  38:     0x7f2930ed003e - g_signal_emit_valist
  39:     0x7f2930ed041e - g_signal_emit
  40:     0x7f293206a2e7 - <unknown>
  41:     0x7f2930ebbac8 - g_object_run_dispose
  42:     0x7f2931f926d9 - <unknown>
  43:     0x7f2931e2d3df - <unknown>
  44:     0x7f2930eb531e - g_closure_invoke
  45:     0x7f2930ec7725 - <unknown>
  46:     0x7f2930ed003e - g_signal_emit_valist
  47:     0x7f2930ed041e - g_signal_emit
  48:     0x7f293206a2e7 - <unknown>
  49:     0x7f2930ebbac8 - g_object_run_dispose
  50:     0x7f2931fb24ff - <unknown>
  51:     0x7f2931e2d3df - <unknown>
  52:     0x7f2930eb531e - g_closure_invoke
  53:     0x7f2930ec7725 - <unknown>
  54:     0x7f2930ed003e - g_signal_emit_valist
  55:     0x7f2930ed041e - g_signal_emit
  56:     0x7f293206a2e7 - <unknown>
  57:     0x7f2930ebbac8 - g_object_run_dispose
  58:     0x7f2931ddded7 - <unknown>
  59:     0x7f2931e2d3df - <unknown>
  60:     0x7f2930eb531e - g_closure_invoke
  61:     0x7f2930ec7725 - <unknown>
  62:     0x7f2930ed003e - g_signal_emit_valist
  63:     0x7f2930ed041e - g_signal_emit
  64:     0x7f293206a2e7 - <unknown>
  65:     0x7f2930ebbac8 - g_object_run_dispose
  66:     0x7f2931ddde8e - <unknown>
  67:     0x7f2931e2d3df - <unknown>
  68:     0x7f2930eb531e - g_closure_invoke
  69:     0x7f2930ec7725 - <unknown>
  70:     0x7f2930ed003e - g_signal_emit_valist
  71:     0x7f2930ed041e - g_signal_emit
  72:     0x7f293206a2e7 - <unknown>
  73:     0x7f2930ebbac8 - g_object_run_dispose
  74:     0x7f29320797c8 - <unknown>
  75:     0x7f2931e2d3df - <unknown>
  76:     0x7f2930eb53c4 - g_closure_invoke
  77:     0x7f2930ec7725 - <unknown>
  78:     0x7f2930ed003e - g_signal_emit_valist
  79:     0x7f2930ed041e - g_signal_emit
  80:     0x7f293206a2e7 - <unknown>
  81:     0x7f293207d09b - <unknown>
  82:     0x7f2930ebbac8 - g_object_run_dispose
  83:     0x7f2931eff5fa - gtk_main_do_event
  84:     0x7f293207a460 - <unknown>
  85:     0x7f29319f35f7 - <unknown>
  86:     0x7f2930be17e9 - g_main_context_dispatch
  87:     0x7f2930be1b9f - <unknown>
  88:     0x7f2930be1ec1 - g_main_loop_run
  89:     0x7f2931efe7b4 - gtk_main
  90:     0x5615e5805165 - rt::main::hd59b8559cda78c56tga
                        at /home/alex/.multirust/toolchains/stable/cargo/git/checkouts/gtk-373d3cc909970d2e/master/src/rt.rs:157
  91:     0x5615e57abbb4 - systemd_gui::launch::h9a78c683f8931ea0pha
                        at src/systemd_gui.rs:446
  92:     0x5615e57a6f18 - main::h59d551a7cc9c3475cqb
                        at src/main.rs:10
  93:     0x5615e5825b34 - sys_common::unwind::try::try_fn::h9896872240422604242
  94:     0x5615e5822dd8 - __rust_try
  95:     0x5615e58257c0 - rt::lang_start::h0d9dcd8707a91319Uoy
  96:     0x5615e57abd49 - main
  97:     0x7f29301b9230 - __libc_start_main
  98:     0x5615e57a6e09 - _start
  99:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/systemd-manager` (exit code: 101)

**Comment by mmstick** [comment] 2016-05-18 03:27
For some reason `gtk::main_quit()` in `window.connect_delete_event()` causes the panic but `gtk::main_quit()` in `window.connect_key_press_event()` does not. I'm not sure how to fix this at the moment, but it's otherwise harmless.

**Comment by mmstick** [comment] 2016-05-19 20:22
I've found the cause and it's fixed now.

**Closed by mmstick** 2016-05-19 20:22 UTC
